# configuration data
bots:
    default: "plugins/ChatCitizen/bots/alice2"
    currentevents: "plugins/ChatCitizen/bots/currentevents"
    jokebot: "plugins/ChatCitizen/bots/jokebot"
    wndef: "plugins/ChatCitizen/bots/wndef"
    soldier: "plugins/ChatCitizen/bots/soldier"
