name: ChatCitizen
main: org.pale.chatcitizen.Plugin
version: 1.3
depend: [Citizens]
commands:
  chatcitizen:
    description: ChatCitizen configuration command
    aliases: [ccz]
    usage: /chatcitizen
    permission: chatcitizen
