name: ChatCitizen
main: org.pale.chatcitizen.Plugin
version: 1.1
depend: [Citizens]
commands:
  ccz:
    description: ChatCitizen configuration command
    usage: /ccz
  chatcitizen:
    description: ChatCitizen configuration command
    usage: /chatcitizen

