name: ChatCitizen
main: org.pale.chatcitizen.Plugin
version: 1.2
depend: [Citizens]
commands:
  ccz:
    description: ChatCitizen configuration command
    usage: /ccz
    permission: chatcitizen
  chatcitizen:
    description: ChatCitizen configuration command
    usage: /chatcitizen
    permission: chatcitizen
